language: node_js

node_js:
  - 'node'

cache:
  directories:
    - client/node_modules
    - server/node_modules

matrix:
  include:
    - name: "Client"
      env: PACKAGE_LOCATION=client
    - name: "server"
      env: PACKAGE_LOCATION=server

script:
  - cd $PACKAGE_LOCATION
  - npm install
  - npm build

git:
  depth: 1